---
version: '3'

services:

  redis-server:
    image: redis:alpine

  app:
    # restart: always
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 9088:8080
    volumes: 
      - $PWD/app:/usr/app/app

